[2024-06-25T08:38:52.097+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T08:38:52.201+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_snowflake_v4.dbt_run manual__2024-06-25T08:38:51.107756+00:00 [queued]>
[2024-06-25T08:38:52.226+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_snowflake_v4.dbt_run manual__2024-06-25T08:38:51.107756+00:00 [queued]>
[2024-06-25T08:38:52.226+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-25T08:38:52.259+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): dbt_run> on 2024-06-25 08:38:51.107756+00:00
[2024-06-25T08:38:52.283+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=941) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-25T08:38:52.285+0000] {standard_task_runner.py:63} INFO - Started process 942 to run task
[2024-06-25T08:38:52.279+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_snowflake_v4', 'dbt_run', 'manual__2024-06-25T08:38:51.107756+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpb4aneoow']
[2024-06-25T08:38:52.289+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask dbt_run
[2024-06-25T08:38:52.436+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_snowflake_v4.dbt_run manual__2024-06-25T08:38:51.107756+00:00 [running]> on host 40877dbc4b09
[2024-06-25T08:38:52.693+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_snowflake_v4' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T08:38:51.107756+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-25T08:38:51.107756+00:00'
[2024-06-25T08:38:52.694+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T08:38:52.806+0000] {docker.py:366} INFO - Starting docker container from image ghcr.io/dbt-labs/dbt-snowflake:latest
[2024-06-25T08:38:52.828+0000] {docker.py:374} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-06-25T08:39:01.424+0000] {docker.py:436} INFO - [0m08:39:01  Running with dbt=1.8.2
[2024-06-25T08:39:02.543+0000] {docker.py:436} INFO - [0m08:39:02  Registered adapter: snowflake=1.8.3
[2024-06-25T08:39:03.629+0000] {docker.py:436} INFO - [0m08:39:03  Found 5 models, 9 data tests, 2 sources, 561 macros
[2024-06-25T08:39:03.634+0000] {docker.py:436} INFO - [0m08:39:03
[2024-06-25T08:39:05.612+0000] {docker.py:436} INFO - [0m08:39:05  Concurrency: 1 threads (target='dev')
[2024-06-25T08:39:05.613+0000] {docker.py:436} INFO - [0m08:39:05
[2024-06-25T08:39:05.650+0000] {docker.py:436} INFO - [0m08:39:05  1 of 5 START sql view model dbt_schema.stg_tpch_line_items ..................... [RUN]
[2024-06-25T08:39:11.720+0000] {docker.py:436} INFO - [0m08:39:11  1 of 5 OK created sql view model dbt_schema.stg_tpch_line_items ................ [[32mSUCCESS 1[0m in 6.06s]
[2024-06-25T08:39:11.723+0000] {docker.py:436} INFO - [0m08:39:11  2 of 5 START sql view model dbt_schema.stg_tpch_orders ......................... [RUN]
[2024-06-25T08:39:12.580+0000] {docker.py:436} INFO - [0m08:39:12  2 of 5 OK created sql view model dbt_schema.stg_tpch_orders .................... [[32mSUCCESS 1[0m in 0.84s]
[2024-06-25T08:39:12.588+0000] {docker.py:436} INFO - [0m08:39:12  3 of 5 START sql table model dbt_schema.int_order_items ........................ [RUN]
[2024-06-25T08:39:22.186+0000] {docker.py:436} INFO - [0m08:39:22  3 of 5 OK created sql table model dbt_schema.int_order_items ................... [[32mSUCCESS 1[0m in 9.60s]
[2024-06-25T08:39:22.190+0000] {docker.py:436} INFO - [0m08:39:22  4 of 5 START sql table model dbt_schema.int_order_items_summary ................ [RUN]
[2024-06-25T08:39:24.229+0000] {docker.py:436} INFO - [0m08:39:24  4 of 5 OK created sql table model dbt_schema.int_order_items_summary ........... [[32mSUCCESS 1[0m in 2.03s]
[2024-06-25T08:39:24.239+0000] {docker.py:436} INFO - [0m08:39:24  5 of 5 START sql table model dbt_schema.fct_orders ............................. [RUN]
[2024-06-25T08:39:26.438+0000] {docker.py:436} INFO - [0m08:39:26  5 of 5 OK created sql table model dbt_schema.fct_orders ........................ [[32mSUCCESS 1[0m in 2.17s]
[2024-06-25T08:39:26.450+0000] {docker.py:436} INFO - [0m08:39:26
[2024-06-25T08:39:26.454+0000] {docker.py:436} INFO - [0m08:39:26  Finished running 2 view models, 3 table models in 0 hours 0 minutes and 22.81 seconds (22.81s).
[2024-06-25T08:39:26.600+0000] {docker.py:436} INFO - [0m08:39:26
[2024-06-25T08:39:26.601+0000] {docker.py:436} INFO - [0m08:39:26  [32mCompleted successfully[0m
[2024-06-25T08:39:26.602+0000] {docker.py:436} INFO - [0m08:39:26
[2024-06-25T08:39:26.604+0000] {docker.py:436} INFO - [0m08:39:26  Done. PASS=5 WARN=0 ERROR=0 SKIP=0 TOTAL=5
[2024-06-25T08:39:29.789+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T08:39:29.830+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt_snowflake_v4, task_id=dbt_run, run_id=manual__2024-06-25T08:38:51.107756+00:00, execution_date=20240625T083851, start_date=20240625T083852, end_date=20240625T083929
[2024-06-25T08:39:29.861+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-25T08:39:29.893+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-25T08:39:29.897+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
